In [2]:

import torch



In [12]:
x = torch.rand(3)
y = torch.rand(3,4)

z = x@y
z.size()

torch.Size([4])

In [16]:
x = torch.randn(3,4)
y = x.view(2,-1,2)
y

tensor([[[-0.8685,  0.2155],
         [ 0.5372,  2.2029],
         [-1.2714, -1.4638]],

        [[-1.5969, -1.1011],
         [-0.7101,  1.1192],
         [-1.4478, -1.8410]]])

In [36]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8]])
print(x)
y = x.squeeze()
print(y)
z = y.unsqueeze(1)
print(z)
w = z.expand(2,5,4)
w

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[[1., 2., 3., 4.]],

        [[5., 6., 7., 8.]]])


tensor([[[1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[5., 6., 7., 8.],
         [5., 6., 7., 8.],
         [5., 6., 7., 8.],
         [5., 6., 7., 8.],
         [5., 6., 7., 8.]]])

In [56]:
x = torch.triu(torch.ones(2,3))
print(f"{x}, {x.size()}")
y = x.transpose(-1, -2)
print(f"{y}, {y.size()}")

print(y[0:1,:])

# print(x@y[0,:])

print(torch.matmul(x, y[0:3, :]))

tensor([[1., 1., 1.],
        [0., 1., 1.]]), torch.Size([2, 3])
tensor([[1., 0.],
        [1., 1.],
        [1., 1.]]), torch.Size([3, 2])
tensor([[1., 0.]])
tensor([[3., 2.],
        [2., 2.]])
